name: OOXMLValidator Tests

on:
  push:
    branches: [main, fix/cli-build]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
env:
  AZURE_FUNCTIONAPP_NAME: OOXMLValidator  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root

jobs:
  test:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
        dotnet-version:
          - 8.x
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup DotNet ${{ matrix.dotnet-version }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build/linux-x64
        run: dotnet publish --framework net8.0 -c Release -r linux-x64 OOXMLValidator.sln
      - name: Build/oxs-x64
        run: dotnet publish --framework net8.0 -c Release -r oxs-x64 OOXMLValidator.sln
      - name: Build/win-x64
        run: dotnet publish --framework net8.0 -c Release -r win-x64 OOXMLValidator.sln
      # - run: find ./OOXMLValidatorCLI/bin/Release/OOXMLValidatorCLI/bin/Release//net8.0/linux-x64/publish/OOXMLValidatorCLI
      - name: Build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ./OOXMLValidatorCLI/bin/Release/net8.0/linux-x64/publish/OOXMLValidatorCLI
            ./OOXMLValidatorCLI/bin/Release/net8.0/oxs-x64/publish/OOXMLValidatorCLI
            ./OOXMLValidatorCLI/bin/Release/net8.0/win-x64/publish/OOXMLValidatorCLI
        
